config/routes.rb
Rails.application.routes.draw do
  root "payments#index"
  post "/payments", to: "payments#create"
  get "/payments/:id", to: "payments#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  # Active record validation for payment
  validates :card_number, presence: true, length: { is: 16 }
  validates :expiry_date, presence: true, length: { is: 4 }
  validates :email_address, format: { with: /\A(.+)@(.+)\z/, message: "Email invalid"  }, length: { minimum: 4, maximum: 254 }
  # validates :email_address, email: true, length: { maximum: 100 }
  validates :name_on_card, :billing_address, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
  end

  def create
    card_number = params[:card_number]
    if card_number == "5560000000000001"
      render :json => "Faild to proceed!", :status => 400
    else
      payment = Payment.new
      # mask credit card number
      card_number.gsub!(/.(?=....)/, '*')
      payment.card_number = card_number
      payment.name_on_card = params[:name_on_card]
      payment.expiry_date = params[:expiry_date]
      payment.email_address = params[:email_address]
      payment.billing_address = params[:billing_address]
      payment.description = params[:description]
      
      if payment.save
        render :json => "/payments/#{payment.id}"
      else
        render :json => payment.errors, :status => 400
      end
    end
  end

  def show
    @payment = Payment.find_by(id: params[:id])
    if @payment.nil?
      redirect_to root_url
    end
  end

  private
    # strong parameters for payment
    def payment_params
      params.require(:payment).permit(:card_number, :name_on_card, :expiry_date, :email_address, :billing_address, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JetPayments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1 class="text-center my-4 text-primary text-uppercase">Jet payments</h1>
      <div data-behavior="vue-app">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/payments/index.html.erb
<payment
  pay_url="<%= payments_path %>"  
></payment>

app/views/payments/show.html.erb
  <h4>Congratulations <span class="text-primary text-capitalize"><%= @payment.name_on_card %></span></h4>
  <p>Your payment has been done successfully! Please check your payment details below:</p>
  <div class="row justify-content-center border-top border-bottom mb-4">
    <div class="p-4">
      <p class="d-table-row"><span class="d-table-cell pr-4 font-weight-bold">ID:</span> <span class="table-cell"><%= @payment.id %></span></p>
      <p class="d-table-row"><span class="d-table-cell pr-4 font-weight-bold">Card Number:</span> <span class="table-cell"><%= @payment.card_number.gsub(/(.{4})(?=.)/, '\1 \2') %></span> </p>
      <p class="d-table-row"><span class="d-table-cell pr-4 font-weight-bold">Email Address:</span> <span class="table-cell"><%= @payment.email_address %></span> </p>
      <p class="d-table-row"><span class="d-table-cell pr-4 font-weight-bold">Billing Address:</span> <span class="table-cell"><%= @payment.billing_address %></span> </p>
      <% if not @payment.description.blank? %>
        <p class="d-table-row"><span class="d-table-cell pr-4 font-weight-bold">Description:</span><%= @payment.description %></p>
      <% end %>
    </div>
  </div>

<%= link_to "Home", root_path %>